import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Header from "@/components/UI/Header";
import Footer from "@/components/UI/Footer";

// Layout Component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-black text-white`}>
        <Header />
        <main className="min-h-screen">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
